[package]
name = "animator"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ezing = "0.2.1"
lerp = "0.5.0"
num-traits = "0.2.17"
sfml = "0.21.0"
